apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: gcr.io/enhanced-skill-453411-t9/hello_app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "104.155.182.203,127.0.0.1,localhost"
            - name: GS_BUCKET_NAME
              value: "your-django-static-files"
            - name: GS_PROJECT_ID
              value: "enhanced-skill-453411-t9"
            # Pull these from Kubernetes Secrets
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DATABASE_URL
            - name: GCP_KEY_BASE64
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: GCP_KEY_BASE64
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: LoadBalancer
  selector:
    app: hello-world-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000